AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Test Microservice using AWS Lambda, Go, and Hexagonal architecture

Resources:
  ServiceLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Timeout: 5
