version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - ${HOME}/.aws:/home/vscode/.aws:ro
    command: sleep infinity
