// problem is a minimal implementation of RFC 7807 "Problem Detail" which
// provides a standard interface for error handling in Web APIs.
// See: https://www.rfc-editor.org/rfc/rfc7807
package internal

// Problem represents a response to an HTTP Request which has encountered an
// issue during processing in-line with RFC 7807.
type Problem struct {
	// A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// A URI reference that identifies the specific occurrence of the problem.
	// It may or may not yield further information if dereferenced.
	Instance string `json:"instance,omitempty"`

	// The HTTP status code generated by the origin server for this occurrence of
	// the problem.
	Status int `json:"status,omitempty"`

	// A short, human-readable summary of the problem type. It SHOULD NOT change
	// from occurrence to occurrence of the problem, except for i18n.
	Title string `json:"title"`

	// A URI reference that identifies the problem type.
	Type string `json:"type"`

	// Additional meta-data to help the caller understand the problem, if any.
	Extras map[string]interface{} `json:"extras,omitempty"`
}
